#install third_party libraries
file(COPY ${S} DESTINATION ${IP}/slam/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${B} DESTINATION ${IP}/slam/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${A} DESTINATION ${IP}/slam/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${Z} DESTINATION ${IP}/slam/lib FOLLOW_SYMLINK_CHAIN)
